---
 - hosts: ansibleclient.example.com
   become: true
   tasks:
           - name: Copy using inline content
             ansible.builtin.copy:
                     content: 'The sun come up and then it goes down'
                     dest: /etc/motd.d/banner

